### PR TITLE
feat(events): [PPT-316] custom filter

### PR DESCRIPTION
**Pull request by chillfox**
Allows customizing the query filter.

Requires:
- https://github.com/PlaceOS/office365/pull/37

### CODE REVIEW

**Comment by naqvis** [comment]
Can we have specs pass?

**Comment by chillfox** [comment]
> Can we have specs pass?

@naqvis It will require the linked PR (https://github.com/PlaceOS/office365/pull/37) to be merged first and then shards updated.

**Review by grkek — APPROVED** [review]
This looks good, I will take a look at the actual `list_events` method now.

**Comment by grkek** [comment]
> This looks good, I will take a look at the actual `list_events` method now.

The `list_events` method looks good and the filter usage is proper, odd issues with the specs.

@naqvis your thoughts?

**Pull request merged**
